version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        VARIANT: 16-bullseye
        # Optional Node.js version to install
        NODE_VERSION: "lts/*"
    restart: always
    ports:
      - 3001:3000
    volumes:
      - ..:/workspace:cached  
    command: sleep infinity
    user: node
    environment:
      - CHOKIDAR_USEPOLLING=true